### ISSUE TITLE
Bilder werden als Seiten erfasst. 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/simplestats#13]
IP Address/Pages
Zeigt Requests auf Bilder als Seitenaufrufe. 

<img width="1026" alt="Bildschirmfoto 2020-05-11 um 11 47 08" src="https://user-images.githubusercontent.com/791247/81548263-4f5e5a00-937d-11ea-983c-1d8e73ebbf9e.png">

**Comment by skerbis** [comment]
ping?

**Comment by staabm** [comment]
Ich würde vermuten dass die gezeigten bilder nicht unter dem pfad existieren, deshalb ein fallback passiert der über die index.php läuft

**Comment by skerbis** [comment]
Nein. Das gleiche gilt auch für /media

**Comment by staabm** [comment]
/media läuft vermutlich durch den media manager und wird daher als stats geloggt.

**Comment by skerbis** [comment]
ah ok ... dann ist die Statistik so nicht mehr anwendbar?

**Comment by staabm** [comment]
> dann ist die Statistik so nicht mehr anwendbar?

ich versteh die Aussage nicht. die statistik zählt alles was durch die boot.php des addons bis zu dieser zeile durchkommt: https://github.com/FriendsOfREDAXO/simplestats/blob/abd6819b6909f3ec1218d9d53096b1f063482161/boot.php#L41

was genau führt dazu dass "die statistik nicht anwendbar ist"? was bedeutet das?

**Comment by skerbis** [comment]
Na ja aktuell zeigt die Statistik bei mir nur Bildaufrufe. Keine Seiten. Somit kann man schwer ermitteln welche Seiten tatsächlich relevant sind.

**Comment by staabm** [comment]
D.h. Wolltest du nur artikel aus der struktur in der statistik haben?

**Comment by skerbis** [comment]
Kommt drauf an. Denke dass da gesplittet werden müsste

**Comment by staabm** [comment]
konkrete verbesserungsvorschläge sind willkommen
