### ISSUE TITLE
Maxmind GeoIP Datenbank ist kein .dat mehr

### ISSUE THREAD

**Issue by Markus-GS** [FriendsOfREDAXO/simplestats#14]
... sondern ein GeoLite2-Country.**mmdb**

https://blog.maxmind.com/2018/01/02/discontinuation-of-the-geolite-legacy-databases/

https://github.com/sherpya/geolite2legacy

**Comment by staabm** [comment]
d.h. was willst du damit sagen? welche auswirkung hat dies auf das addon?

**Comment by Markus-GS** [comment]
Du kannst nicht mehr einfach das ".dat" mit den aktuellen GeoIP Daten saugen und einspielen.
Entweder wandelt man es manuell von mmdb nach dat oder das GeoIP Interface im Addon wird nach GeoIP2 umgebastelt, so daß die mmdb direkt gelesen werden kann.

https://maxmind.github.io/GeoIP2-php/

**Comment by staabm** [comment]
Nutzt du das addon? Willst du einen fix beisteuern?
