### ISSUE TITLE
PHP 8 :: Array and string offset access syntax with curly braces

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/simplestats#15]
09.12.2020 12:09:19 | Fatal error | Array and string offset access syntax with curly braces is no longer supported | redaxo/src/addons/simplestats/vendor/dshafik/php7-mysql-shim/lib/mysql.php | 58
-- | -- | -- | -- | --

**Comment by staabm** [comment]
der fehler ist hier zu suchen: https://github.com/dshafik/php7-mysql-shim

**Comment by skerbis** [comment]
https://github.com/dshafik/php7-mysql-shim/releases
