### ISSUE TITLE
Unter PHP 8 und 8.1 geht das Add-on nicht mehr.

### ISSUE THREAD

**Issue by jungcreative** [FriendsOfREDAXO/simplestats#17]
`Open: /redaxo/src/addons/simplestats/vendor/dshafik/php7-mysql-shim/lib/mysql.php

            $password = null,
            $new = false,
            $flags = 0
        ) {
            if ($new !== false) {
                trigger_error('Argument $new is no longer supported in PHP > 7', E_USER_WARNING);
            }
            if (null === $hostname) {
                $hostname = ini_get('mysqli.default_host') ?: null;
            }
            if (null === $username) {
                $username = ini_get('mysqli.default_user') ?: null;
            }
            if (null === $password) {
                $password = ini_get('mysqli.default_pw') ?: null;
            }
 
            $hash = sha1($hostname . $username . $flags);
            /* persistent connections start with p: */
            if ($hostname{1} !== ':' && isset(\Dshafik\MySQL::$connections[$hash])) {
                \Dshafik\MySQL::$last_connection = \Dshafik\MySQL::$connections[$hash]['conn'];
                \Dshafik\MySQL::$connections[$hash]['refcount'] += 1;
                return \Dshafik\MySQL::$connections[$hash]['conn'];
            }
 
            /* No flags, means we can use mysqli_connect() */
            if ($flags === 0) {
                $conn = mysqli_connect($hostname, $username, $password);
                if (!$conn instanceof mysqli) {
                    return false;
                }
                \Dshafik\MySQL::$last_connection = $conn;
                $conn->hash = $hash;
                \Dshafik\MySQL::$connections[$hash] = array('refcount' => 1, 'conn' => $conn);
 
                return $conn;
            }
 
            /* Flags means we need to use mysqli_real_connect() instead, and handle exceptions */
            try {

Arguments

    "Array and string offset access syntax with curly braces is no longer supported"`

**Comment by staabm** [comment]
Vermutlich müsste die mysql-shim lib im addon upgedated werden:

https://github.com/dshafik/php7-mysql-shim

**Comment by jungcreative** [comment]
Habe ich gemacht. Nun kommt eine weitere Error Meldung begzüglich PHP8

` Open: /redaxo/src/addons/simplestats/vendor/staabm/simple-stats/index.php

<?php
/**
 * Simple Stats: PHP web statistics software. See the license.txt file for copyright and licensing information.
 */

 
if ( get_magic_quotes_gpc() ) {
    foreach ( array_keys( $_GET ) as $key ) 
        $_GET[$key] = stripslashes( $_GET[$key] );
    foreach ( array_keys( $_POST ) as $key ) 
        $_POST[$key] = stripslashes( $_POST[$key] );
    foreach ( array_keys( $_COOKIE ) as $key )
        $_COOKIE[$key] = stripslashes( $_COOKIE[$key] );
    $_REQUEST = array_merge( $_GET, $_POST );
}
 
define( 'SIMPLE_STATS_PATH', realpath( dirname( __FILE__ ) ) );
 
if( file_exists( SIMPLE_STATS_PATH.'/config.php' ) )
    require_once( SIMPLE_STATS_PATH.'/config.php' );
require_once( SIMPLE_STATS_PATH.'/includes/classes.php' );
require_once( SIMPLE_STATS_PATH.'/includes/ua.php' );
require_once( SIMPLE_STATS_PATH.'/includes/functions.php' );
include_once( SIMPLE_STATS_PATH.'/includes/countries.php' );
 
$page = ( isset( $_GET['p'] ) && in_array( $_GET['p'], array( 'paths', 'overview', 'options', 'js', 'login', 'logout' ) ) ) ? $_GET['p'] : 'overview';
 
$ss = new SimpleStats();
 
if( !$ss->is_installed() ) {
    // check whether we've just finished setup
    if( isset( $_POST['action'] ) && $_POST['action'] == 'complete_setup' ) {
        $ss->setup_options();
    }
    else {
        $page = 'setup';
        require_once( SIMPLE_STATS_PATH.'/includes/setup.php' );
        exit;
    }
}
 

Arguments

    "Call to undefined function get_magic_quotes_gpc()"
`

**Comment by staabm** [comment]
Fix in https://github.com/staabm/Simple-Stats/commit/8747386c7ec5cde34d8d62f6b13132d992325fd4

**Comment by staabm** [comment]
@jungcreative kannst du nen PR schicken der die 2 dependencies hier im addon updated?

**Comment by jungcreative** [comment]
Hi... Läuft noch nicht ganz ... 

` Open: /www/htdocs/w01848bf/jungcreative/jc/redaxo/src/addons/simplestats/vendor/staabm/simple-stats/includes/overview.php

            
            // these items don't have an "Unknown" category
            if( in_array( $field, array( 'search_terms', 'referrer', 'domain' ) ) && empty( $value ) )
                continue;
            
            // store version as Browser => array( version => hits )
            if ( $field == 'version' ) {
                $browser = $row['browser'];
                if ( !isset( $visits[$field][$browser] ) ) 
                    $visits[$field][$browser] = array();
                
                if ( isset( $visits[$field][$browser][$value] ) )
                    $visits[$field][$browser][$value] ++;
                else
                    $visits[$field][$browser][$value] = 1;
                continue;
            }
 
            if ( isset( $visits[$field][$value] ) )
                $visits[$field][$value] ++;
            else
                $visits[$field][$value] = 1;
        }
    }
 
    return array( 'visits' => $visits, 'pages' => $pages );;
}
 
function valid_dy( $_dy, $_mo, $_yr ) {
    $dy = max( 1, min( date( 'j', gmmktime( 12, 0, 0, $_mo + 1, 0, $_yr ) ), intval( $_dy ) ) );
    if ( $_yr == date( 'Y' ) && $_mo == date( 'n' ) )
        $dy = min( date( 'j' ), $dy );
 
    return $dy;
}
 
function valid_mo( $_mo ) {
    return max( 1, min( 12, intval( $_mo ) ) );
}
 

Arguments

    "Cannot increment array"
`
