### ISSUE TITLE
mbstring als extension 

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/simplestats#2]
In die package.yml, da benötigt für PHP simple stats (außer es ist bereits Pflicht für Redaxo)

**Comment by staabm** [comment]
die simple stats lib hat leider aktuell etliche abhängigkeiten. da ich mich bereits entschlossen habe die lib zu forken werden ich dort ggf. ein paar loswerden.

**Comment by gharlan** [comment]
zu mbstring: das liefert redaxo als polyfill mit.
