### ISSUE TITLE
Screenshots in d. Readme

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/simplestats#3]
@schuer vllt ;)

**Comment by schuer** [comment]
Ich wollte neulich schonmal Screenshots machen, habe dann aber gemerkt, dass ich nirgendwo Daten habe, die die Stats in Aktion zeigen. Die Entwickler stellen leider auch keine Demo-Version zur Ansicht, zumindest habe ich keine gefunden.

Wir bräuchten also eine Installation mit Daten. Hat jemand von euch die Simplestats im Einsatz?

**Comment by staabm** [comment]
fixed in https://github.com/FriendsOfREDAXO/simplestats/commit/d36abb10cb3b596066802413fff912e61e194330

**Comment by staabm** [comment]
DANKE!
