### ISSUE TITLE
Erste Release?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/simplestats#6]
Ist es schon soweit, dass ein erstes Release gemacht werden kann? Bestimmt, oder?
Danach kann auch das Küken aus der Beschreibung entfernt werden ;)

**Comment by staabm** [comment]
jepp, kann man machen. 0.1 oder sowas.

**Comment by schuer** [comment]
Lieber 1.0, oder? ;)
Ich bin auch wieder weg, kann mich aber heute abend mal drum kümmern.

**Comment by staabm** [comment]
Jop

**Comment by schuer** [comment]
✅ Done.
