### ISSUE TITLE
Setup Screen erscheint auch wenn das Setup bereits durchgeführt wurde

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/simplestats#7]
... ein anschließender Click auf 'Next step' zeigt dann aber die Addon Seite
![image](https://cloud.githubusercontent.com/assets/1148347/24598732/4aa6814e-184d-11e7-8e5c-f60700732e71.png)

**Comment by staabm** [comment]
d.h. es geht bei dir gar nicht oder es gibt "nur probleme" im initialen setup wenn man auf "next step" clicked?

**Comment by isospin** [comment]
das initiale setup läuft problemlos durch.
das addon funktioniert auch. 
allerdings kommt der erste setup screen wieder, wenn ich das addon später wieder öffne.  wenn ich dann auf 'next step' klicke komme ich auf die addon page (ohne das das setup nochmals durchläuft).

**Comment by staabm** [comment]
die datenbanktabellen wurden richtig angelegt? verwendest du ggf. nen tableprefix der unterschiedlich ist vom "default" (also nicht "rex"?)

**Comment by isospin** [comment]
nein, kein custom prefix. ja, sieht so aus als wenn die tabellen richtig angelegt den:
rex_simple_stats_archive, rex_simple_stats_options und rex_simple_stats_visits
