### ISSUE TITLE
Setup bricht ab mit error

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/simplestats#8]
Auf der 2.Seite des Setup **/redaxo/?page=simplestats&p=setup** bricht der Install ab; einziges lebenszeichen:

`{"error":"Ein Fehler ist aufgetreten."}`

**Comment by staabm** [comment]
php version? rex-version? systemlog irgendwas drinn?

table-prefix im einsatz?

**Comment by cukabeka** [comment]
REDAXO
5.3.0

PHP
5.6.29

Systemlog ist leer, Table-Prefix ist nur das reguläre rex_
